services:
  lenzbriefestaging:
    build: .
    expose:
      - "8085"
    volumes:
      - lenz_briefe_staging:/app/data
    networks:
      - caddynet

volumes:
  lenz_briefe_staging:
    external: true

networks:
  caddynet:
    external: true
